services:
  db:
    image: postgres:16
    container_name: spaceweather_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spaceweather
    ports:
      - "5432:5432"
    volumes:
      - sw_pgdata:/var/lib/postgresql/data

volumes:
  sw_pgdata:
